kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: ht-pvc
spec:
  storageClassName: local-storage-01
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 512Mi