kind: PersistentVolume
apiVersion: v1
metadata:
  name: ht-pv
spec:
  storageClassName: local-storage-01
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/k8svol/local-storage-01"